---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supes-villain-database
spec:
  selector:
    matchLabels:
      app: supes-villain-database
  template:
    metadata:
      labels:
        app: supes-villain-database
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: supes-villain
            - name: POSTGRES_USER
              value: supes
            - name: POSTGRES_PASSWORD
              value: supes

---
apiVersion: v1
kind: Service
metadata:
  name: supes-villain-database
spec:
  ports:
    - port: 5432
  selector:
    app: supes-villain-database